# Site settings
title: Ontodia
logo: "/assets/img/logo.png"
description: "Description"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://ontodia.org/"
timezone: UTC
future: true

paginate: 2
paginate_path: "blog/page:num/"

disqus_shortname: ontodia


# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!-- more -->
sass:
  sass_dir: _sass
  style: compressed


# Navigation
navigation:
  - title: Home
    url: "/"
  - title: Blog
    url: "/blog/"
    layouts: [blog, post]
  - title: About
    url: "/about/"


# Social
social:
  - title: facebook
    url:
  - title: twitter
    url:

# Contributors
contributors:
  - title: Vismart Ltd.
    url: "http://www.vismart.biz"
  - title: ITMO University
    url: "http://www.ifmo.ru"
    
# Quick links
quick_links:
  - title: About
    url: "/about/"
  - title: Blog & Tutorials
    url: "/blog/"
    
# Contact us
contact_us:
  - title: Vismart Ltd.
    emails:
      - title: info@vismart.biz
        url: "https://groups.google.com/forum/#!forum/ontodia"
      - title: www.vismart.biz
        url: "http://www.vismart.biz"
  
  
gems: [jekyll-paginate, jekyll-autoprefixer]    