# Site settings
title: Ontodia
logo: "/assets/img/logo.png"
description: "Description"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: http://ontodia.org
timezone: UTC
future: true

paginate: 2
paginate_path: "blog/page:num/"

disqus_shortname: 'ontodia'


# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!-- more -->
sass:
  sass_dir: _sass
  style: compressed


# Navigation
navigation:
  - title: Home
    url: "/"
  - title: Blog
    url: "/blog/"
    layouts: [blog, post]
  - title: About
    url: "/about/"
  - title: Projects
    url: "/projects/"
  - title: GitHub
    url: "https://github.com/ontodia-org/ontodia"


# Social
social:
  - title: facebook
    url:
  - title: twitter
    url:

# Contributors
# contributors:
#  - title: VISmart Ltd.
#  url: "http://www.vismart.biz"
    
# Quick links
quick_links:
  - title: About
    url: "/about/"
  - title: Blog & Tutorials
    url: "/blog/"
  - title: Projects
    url: "/projects/"

# Contact us
contact_us:   
  - title: VISmart Ltd.
    emails:
      - title: dmitry.pavlov@ontodia.org
        url: "mailto:dmitry.pavlov@ontodia.org"
      #- title: www.vismart.biz
       # url: "http://www.vismart.biz"
  
  
gems: [jekyll-paginate, jekyll-autoprefixer]    
